version: '3.8'

networks:
  web:
    external: true

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bros-code-webapp
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'

      # Middleware — jedinstven naziv
      - "traefik.http.middlewares.broscode-wwwtoapex.redirectregex.regex=^https?://www\\.bros-code\\.com/(.*)"
      - 'traefik.http.middlewares.broscode-wwwtoapex.redirectregex.replacement=https://bros-code.com/$1'

      # Router — jedinstven
      - 'traefik.http.routers.broscode.rule=Host(`bros-code.com`,`www.bros-code.com`)'
      - 'traefik.http.routers.broscode.entrypoints=websecure'
      - 'traefik.http.routers.broscode.tls=true'
      - 'traefik.http.routers.broscode.tls.certresolver=myresolver'
      - 'traefik.http.routers.broscode.middlewares=broscode-wwwtoapex'

      # Service — jedinstven
      - 'traefik.http.services.broscode.loadbalancer.server.port=3000'
